# Numpy Library

## Installation

```bash
pip install numpy
```

## Usage

The most important data type in Numpy, is Numpy **array/matrix**.
It can be defined using the following methods:


In [1]:
import numpy as np

# From a current python list
py_list = [1, 2, 3, 4]
np.array(py_list)

array([1, 2, 3, 4])

In [2]:
# A list with all the numbers being the same
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
# a range of numbers (similar to python range function)
### start = 1, stop = 10, step = 1
### IMPORTANT: stop is EXCLUSIVE like python
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Why NumPy array? What is the difference between NumPy array and python list?

Python list, is a general type for many different operations, NumPy is more optimized for calculations.

- Different behavior compared to list make it a better option for calculation
- Much faster compared to regular python list

#### Different Behavior

In [ ]:
# Adding a number to the list/array

##### In Numpy
np_res = 5 + np.array([1, 2, 3])
print(f"numpy result: {np_res}")

##### In Python (will generate an error)
5 + [1, 2, 3]

numpy result: [6 7 8]


TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [ ]:
# multiplying the list/array

##### In Numpy
np_res = 5 * np.array([1, 2, 3])
print(f"numpy result: {np_res}")

##### In Python
py_res = 5 * [1, 2, 3]
print(f"python result: {py_res}")

numpy result: [ 5 10 15]
python result: [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


#### Performance Difference
The performance is also much better in NumPy.

In [ ]:
import math
import time

size = 1000000

my_list = []
for i in range(1, size):
    my_list.append(i)

start_time_python_list = time.perf_counter_ns()
square_root_list = []
for i in my_list:
    square_root_list.append(math.sqrt(i))
end_time_python_list = time.perf_counter_ns()

elapsed_time = end_time_python_list - start_time_python_list
print(f"elapsed time for python list (ns): {elapsed_time}")

elapsed time for python list (ns): 96381300


In [ ]:
my_np_arr = np.arange(size)
start_time_np_arr = time.perf_counter_ns()
square_root_np = np.sqrt(my_np_arr)
end_time_np_arr = time.perf_counter_ns()


elapsed_time = end_time_np_arr - start_time_np_arr
print(f"elapsed time for numpy array (ns): {elapsed_time}")

elapsed time for numpy array (ns): 2883000


In [ ]:
np_arr = np.array([1, 2, 3])

# Access element with index0
single_access = np_arr[0]
print(f"single_access = {single_access}")
# Range access
range_access = np_arr[0:2]
print(f"range_access = {range_access}")
